In [1]:

import os
# Make sure you are in scMEDAL_for_scRNAseq dir
os.chdir("/archive/bioinformatics/DLLab/AixaAndrade/src/gitfront/dev2/scMEDAL_for_scRNAseq")

from models.models import train_model_on_named_experiment

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/tensorflow_addons/utils/tfa_eol_msg.py:23: UserWarning:

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP).

For more information see: https://github.com/tensorflow/addons/issues/2807

  warnings.warn(
WARNING:absl:`lr` is deprecated in Keras optimizer, please use `learning_rate` or use the legacy optimizer, e.g.,tf.keras.optimizers.legacy.Adam.
WARNING:absl:`lr` is deprecated in Keras optimizer, please use `learning_rate` or use the legacy optimizer, e.g.,tf.keras.optimizers.legacy.Adam.
WARNING:absl:`lr` is deprecated in Keras optimizer, please use `learning_rate` or use the legacy optimizer, e.g.,tf.keras.optimizers.legacy.Adam.

OUTPUTS_DIR: /endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/outputs

In [2]:

os.getcwd()

'/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq'

## Training Models:

#### Implemented Models:
| Model Class | Model Description | 
|------------|--------------------|  
| `AE` | Autoencoder | 
| `AEC`| Autoencoder Classifier |
| `scMEDAL-FE` | Domain Adversarial Autoencoder |
| `scMEDAL-FEC`| Domain Adversarial Autoencoder Classifier |
| `scMEDAL-RE`| Domain Enhancing Autoencoder Classifier | 

#### Named Experiments:
| Valid Named Experiment | Dataset |  n_clusters | n_pred |
|------------------------|---------|-------------|--------|
| `AML`| Acute Myeloid Leukemia | 19 | 21 |
| `ASD`| Autism Spectrum Disorder | 31 | 17 | 
| `HH` | Healthy Heart | 147 | 13 | 

**Note:** If training on other datasets, the configs will need to be passed in as dictionaries to `model_kwargs` and `train_kwargs`.

`quick` is a boolean flag that can be passed to `train_kwargs` which shortens training to only 1 fold for 3 epochs.

Run models on all 3 datasets with

$python\ run\_scMEDAL\_alldatasets.py$

## Analyzing Models:

When you run a model, it generates the following output directories:
   - /outputs/figures
   - /outputs/latent_space
   - /outputs/saved_models
 
 Inside each of these directories, there is a subdirectory named after the model and its run identifier.
 
 For example: $HH/latent\_space/scmedalfe/run\_crossval\_<run\_name>$

 To analyze your results, copy the corresponding $<run\_name>$ below.

In [3]:

# When you run your model, it outputs the figures, latent_space and saved_models directories, whitin those directories you will find a subdir with the name of the model trained, example: AML/latent_space/scmedalfe/run_crossval_<run_name>
# Please copy the <run_name below> to analyze the results
# Update output paths of the models that you just run

from utils.defaults import HH_OUTPUTS_DIR, HH_EXPERIMENT_NAME
print(f"Loading outputs from {HH_OUTPUTS_DIR}. Please verify that your models output folder is located here before proceeding with the analysis.")
import os
model_folder_dict = {
    "ae":"run_crossval_n_latent_dims-50_layer_units-512-132_use_batch_norm-True_scaling-min_max_model_type-ae_batch_size-512_epochs-500_patience-30_compute_latents_callback-False_sample_size-10000_n_components-50_get_cf_batch-False_2025-07-10_07-59",
    "aec":"run_crossval_n_latent_dims-50_layer_units-512-132_n_pred-13_use_batch_norm-True_scaling-min_max_model_type-aec_batch_size-512_epochs-500_patience-30_compute_latents_callback-False_sample_size-10000_get_cf_batch-False_2025-07-10_11-04",
    "scmedalfe":"run_crossval_loss_gen_weight-1_loss_recon_weight-600_loss_class_weight-1_n_latent_dims-50_layer_units-512-132_scaling-min_max_model_type-scmedalfe_batch_size-512_epochs-500_patience-30_sample_size-10000_2025-07-10_02-47",
    "scmedalfec":"run_crossval_loss_gen_weight-1_loss_recon_weight-2000_loss_class_weight-1_n_latent_dims-50_layer_units-512-132_scaling-min_max_model_type-scmedalfec_batch_size-512_epochs-500_patience-30_sample_size-10000_get_cf_batch-False_2025-07-10_14-36",
    "scmedalre":"run_crossval_loss_recon_weight-110_loss_latent_cluster_weight-0.1_n_latent_dims-50_layer_units-512-132_scaling-min_max_batch_size-512_epochs-500_patience-30_sample_size-10000_2025-07-09_22-05",
    # To collect the comparable outputs (see below), you need to run the comparable models in /comparables. 
    "scVI":"run_crossval_n_latent_dims-50_n_layers-2_n_hidden-132_gene_likelihood-zinb_dispersion-gene_scaling-min_max_batch_size-512_epochs-500_patience-30_compute_latents_callback-False_sample_size-10000_model_type-ae_tissue_col-TissueDetail_2025-06-17_13-37",
    "scANVI":"run_crossval_n_latent_dims-50_n_layers-2_n_hidden-132_gene_likelihood-zinb_dispersion-gene_scaling-min_max_batch_size-512_epochs-500_patience-30_compute_latents_callback-False_sample_size-10000_model_type-ae_tissue_col-TissueDetail_2025-06-24_23-13",
    "scanorama":"run_crossval_n_latent_dims-50_scaling-min_max_sample_size-10000_model_type-ae_tissue_col-TissueDetail_2025-06-17_17-08",
    "harmony":"run_crossval_n_latent_dims-50_scaling-min_max_sample_size-10000_model_type-ae_tissue_col-TissueDetail_2025-06-24_23-22",
    "SAUCIE":"run_crossval_n_latent_dims-50_layers-512-132-50_lambda_b-0.0_lambda_c-0.0_lambda_d-0.0_learning_rate-0.0_scaling-min_max_batch_size-512_epochs-50_patience-30_sample_size-10000_model_type-ae_tissue_col-TissueDetail_2025-06-26_13-40",
    }

model_paths = {k:os.path.join(HH_OUTPUTS_DIR, "latent_space", HH_EXPERIMENT_NAME,k, v) for k, v in model_folder_dict.items()}

Loading outputs from /endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/HH. Please verify that your models output folder is located here before proceeding with the analysis.

In [4]:
model_paths

{'ae': '/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/HH/latent_space/log_transformed_3000hvggenes/ae/run_crossval_n_latent_dims-50_layer_units-512-132_use_batch_norm-True_scaling-min_max_model_type-ae_batch_size-512_epochs-500_patience-30_compute_latents_callback-False_sample_size-10000_n_components-50_get_cf_batch-False_2025-07-10_07-59',
 'aec': '/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/HH/latent_space/log_transformed_3000hvggenes/aec/run_crossval_n_latent_dims-50_layer_units-512-132_n_pred-13_use_batch_norm-True_scaling-min_max_model_type-aec_batch_size-512_epochs-500_patience-30_compute_latents_callback-False_sample_size-10000_get_cf_batch-False_2025-07-10_11-04',
 'scmedalfe': '/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/HH/latent_space/log_transformed_3000hvggenes/scmedalfe/run_crossval_loss_gen_weight-1_loss_recon_weight-600_loss_class_weight-1_n_latent_dims-50_layer_units-512-132_scaling-min_max_model_type-scmedalfe_batch_size-512_epochs-500_patience-30_sample_size-10000_2025-07-10_02-47',
 'scmedalfec': '/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/HH/latent_space/log_transformed_3000hvggenes/scmedalfec/run_crossval_loss_gen_weight-1_loss_recon_weight-2000_loss_class_weight-1_n_latent_dims-50_layer_units-512-132_scaling-min_max_model_type-scmedalfec_batch_size-512_epochs-500_patience-30_sample_size-10000_get_cf_batch-False_2025-07-10_14-36',
 'scmedalre': '/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/HH/latent_space/log_transformed_3000hvggenes/scmedalre/run_crossval_loss_recon_weight-110_loss_latent_cluster_weight-0.1_n_latent_dims-50_layer_units-512-132_scaling-min_max_batch_size-512_epochs-500_patience-30_sample_size-10000_2025-07-09_22-05',
 'scVI': '/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/HH/latent_space/log_transformed_3000hvggenes/scVI/run_crossval_n_latent_dims-50_n_layers-2_n_hidden-132_gene_likelihood-zinb_dispersion-gene_scaling-min_max_batch_size-512_epochs-500_patience-30_compute_latents_callback-False_sample_size-10000_model_type-ae_tissue_col-TissueDetail_2025-06-17_13-37',
 'scANVI': '/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/HH/latent_space/log_transformed_3000hvggenes/scANVI/run_crossval_n_latent_dims-50_n_layers-2_n_hidden-132_gene_likelihood-zinb_dispersion-gene_scaling-min_max_batch_size-512_epochs-500_patience-30_compute_latents_callback-False_sample_size-10000_model_type-ae_tissue_col-TissueDetail_2025-06-24_23-13',
 'scanorama': '/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/HH/latent_space/log_transformed_3000hvggenes/scanorama/run_crossval_n_latent_dims-50_scaling-min_max_sample_size-10000_model_type-ae_tissue_col-TissueDetail_2025-06-17_17-08',
 'harmony': '/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/HH/latent_space/log_transformed_3000hvggenes/harmony/run_crossval_n_latent_dims-50_scaling-min_max_sample_size-10000_model_type-ae_tissue_col-TissueDetail_2025-06-24_23-22',
 'SAUCIE': '/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/HH/latent_space/log_transformed_3000hvggenes/SAUCIE/run_crossval_n_latent_dims-50_layers-512-132-50_lambda_b-0.0_lambda_c-0.0_lambda_d-0.0_learning_rate-0.0_scaling-min_max_batch_size-512_epochs-50_patience-30_sample_size-10000_model_type-ae_tissue_col-TissueDetail_2025-06-26_13-40'}

##### Step 1: Import the analysis class and initialize it

In [5]:

import analysis.analysis as aa

analysis_name = "HH_default_500"



hh = aa.HHAnalysis(model_folder_dict, analysis_name)

##### Step 2: Compile clustering scores calculated after training the models

In [6]:


res= hh.clustering_scores(model_folder_dict)
# You can now inspect or export `clustering_results` as needed
# Note: if you only run 1 fold, you will see NAN in CI entries
res

[WARN] scVI: config.json not found: /endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/HH/saved_models/log_transformed_3000hvggenes/scVI/run_crossval_n_latent_dims-50_n_layers-2_n_hidden-132_gene_likelihood-zinb_dispersion-gene_scaling-min_max_batch_size-512_epochs-500_patience-30_compute_latents_callback-False_sample_size-10000_model_type-ae_tissue_col-TissueDetail_2025-06-17_13-37/configs.json  using single-model format (AE will default to PCA format if present)
[WARN] scANVI: config.json not found: /endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/HH/saved_models/log_transformed_3000hvggenes/scANVI/run_crossval_n_latent_dims-50_n_layers-2_n_hidden-132_gene_likelihood-zinb_dispersion-gene_scaling-min_max_batch_size-512_epochs-500_patience-30_compute_latents_callback-False_sample_size-10000_model_type-ae_tissue_col-TissueDetail_2025-06-24_23-13/configs.json  using single-model format (AE will default to PCA format if present)
[WARN] scanorama: config.json not found: /endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/HH/saved_models/log_transformed_3000hvggenes/scanorama/run_crossval_n_latent_dims-50_scaling-min_max_sample_size-10000_model_type-ae_tissue_col-TissueDetail_2025-06-17_17-08/configs.json  using single-model format (AE will default to PCA format if present)
[WARN] harmony: config.json not found: /endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/HH/saved_models/log_transformed_3000hvggenes/harmony/run_crossval_n_latent_dims-50_scaling-min_max_sample_size-10000_model_type-ae_tissue_col-TissueDetail_2025-06-24_23-22/configs.json  using single-model format (AE will default to PCA format if present)
[WARN] SAUCIE: config.json not found: /endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/HH/saved_models/log_transformed_3000hvggenes/SAUCIE/run_crossval_n_latent_dims-50_layers-512-132-50_lambda_b-0.0_lambda_c-0.0_lambda_d-0.0_learning_rate-0.0_scaling-min_max_batch_size-512_epochs-50_patience-30_sample_size-10000_model_type-ae_tissue_col-TissueDetail_2025-06-26_13-40/configs.json  using single-model format (AE will default to PCA format if present)
Directory created or already exists: /endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/HH/compare_models/log_transformed_3000hvggenes/HH_default_500

Computed aggregated scores DataFrame
Computed Confidence interval results for sample size: 10000, saved to: /endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/HH/compare_models/log_transformed_3000hvggenes/HH_default_500

               batch                                                         \
                1/db                        ch                   silhouette
                mean CI_lower CI_upper    mean CI_lower CI_upper       mean
dataset_type
X_pca_test      0.14     0.13     0.14   47.25    46.55    47.96      -0.18
ae_latent_test  0.13     0.13     0.14   50.23    33.88    66.59      -0.17
SAUCIE          0.05     0.02     0.08   16.00     4.42    27.59      -0.52
aec             0.10     0.09     0.11   29.21    21.98    36.45      -0.32
harmony         0.11     0.06     0.15   31.92    11.70    52.13      -0.21
scANVI          0.06     0.05     0.06    7.06     6.01     8.11      -0.52
scVI            0.06     0.05     0.06    5.02     4.36     5.68      -0.49
scanorama       0.12     0.10     0.14   48.17    45.76    50.59      -0.21
scmedalfe       0.10     0.10     0.11   28.55    14.96    42.14      -0.21
scmedalfec      0.12     0.11     0.12   13.87    13.32    14.42      -0.20
scmedalre       0.42     0.37     0.47  333.73   239.78   427.68       0.10

                                 celltype                                      \
                                     1/db                         ch
               CI_lower CI_upper     mean CI_lower CI_upper     mean CI_lower
dataset_type
X_pca_test        -0.19    -0.17     0.40     0.38     0.42   691.12   678.39
ae_latent_test    -0.19    -0.16     0.38     0.34     0.41   796.46   698.29
SAUCIE            -0.67    -0.37     0.24     0.17     0.30   904.14   400.10
aec               -0.37    -0.27     0.54     0.47     0.62  2473.06  1943.55
harmony           -0.28    -0.15     0.27     0.13     0.41   875.22   639.57
scANVI            -0.57    -0.47     0.70     0.64     0.77  3218.83  1791.26
scVI              -0.52    -0.47     0.56     0.52     0.59  2105.31  1886.44
scanorama         -0.27    -0.16     0.40     0.38     0.42   748.77   674.34
scmedalfe         -0.23    -0.19     0.37     0.35     0.39   762.33   612.55
scmedalfec        -0.21    -0.18     0.40     0.39     0.41   679.06   640.22
scmedalre          0.07     0.13     0.20     0.18     0.21   268.98   207.41


                        silhouette
               CI_upper       mean CI_lower CI_upper
dataset_type
X_pca_test       703.84       0.15     0.15     0.15
ae_latent_test   894.64       0.13     0.12     0.14
SAUCIE          1408.19      -0.04    -0.06    -0.01
aec             3002.56       0.32     0.29     0.36
harmony         1110.87       0.13     0.10     0.15
scANVI          4646.40       0.32     0.26     0.38
scVI            2324.17       0.22     0.16     0.27
scanorama        823.20       0.18     0.14     0.22
scmedalfe        912.10       0.10     0.08     0.12
scmedalfec       717.90       0.14     0.14     0.15
scmedalre        330.54      -0.05    -0.07    -0.04

##### Step 3: Generate and save the UMAP plots

In [7]:

# This typically loads latent representations stored after training and creates UMAPs for each model
processors = hh.umap(model_folder_dict, types=["train"], splits=[1])
processors

\plot configs dict_items([('markers', ['x', '+', '<', 'h', 's', '.', 'o', 's', '^', '*', '1', '8', 'p', 'P', 'D', '|', 0, ',', 'd', 2]), ('palette_choice', ['#e6194b', '#3cb44b', '#ffe119', '#4363d8', '#f58231', '#911eb4', '#46f0f0', '#f032e6', '#000000', '#fabebe', '#008080', '#e6beff', '#9a6324', '#d2f53c', '#7fff00', '#000080', '#800000', '#808000', '#800080', '#808080', '#ffd700', '#ff4500', '#00ff7f', '#dda0dd', '#87ceeb', '#00ced1', '#9400d3', '#ff6347', '#4682b4', '#6b8e23', '#a52a2a']), ('showplot', False), ('save_fig', True), ('outpath', None), ('use_bio_bio', True), ('use_batch_batch', True), ('use_bio_batch', False), ('use_batch_bio', False)])

df_latent columns: Index(['Key', 'Split', 'LatentPath', 'Type'], dtype='object')
df_latent:
         Key  Split                                         LatentPath   Type
0        ae      1  /endosome/archive/bioinformatics/DLLab/src/Aix...  train
1        ae      1  /endosome/archive/bioinformatics/DLLab/src/Aix...    val
2        ae      1  /endosome/archive/bioinformatics/DLLab/src/Aix...   test
3        ae      2  /endosome/archive/bioinformatics/DLLab/src/Aix...  train
4        ae      2  /endosome/archive/bioinformatics/DLLab/src/Aix...    val
..      ...    ...                                                ...    ...
145  SAUCIE      4  /endosome/archive/bioinformatics/DLLab/src/Aix...    val
146  SAUCIE      4  /endosome/archive/bioinformatics/DLLab/src/Aix...   test
147  SAUCIE      5  /endosome/archive/bioinformatics/DLLab/src/Aix...  train
148  SAUCIE      5  /endosome/archive/bioinformatics/DLLab/src/Aix...    val
149  SAUCIE      5  /endosome/archive/bioinformatics/DLLab/src/Aix...   test

[150 rows x 4 columns]

df_inputs columns: Index(['Split', 'Type', 'InputsPath'], dtype='object')
df_inputs:
    Split   Type                                         InputsPath
0      1  train  /archive/bioinformatics/DLLab/AixaAndrade/src/...
1      1    val  /archive/bioinformatics/DLLab/AixaAndrade/src/...
2      2  train  /archive/bioinformatics/DLLab/AixaAndrade/src/...
3      2    val  /archive/bioinformatics/DLLab/AixaAndrade/src/...
4      3  train  /archive/bioinformatics/DLLab/AixaAndrade/src/...
5      3    val  /archive/bioinformatics/DLLab/AixaAndrade/src/...
6      4  train  /archive/bioinformatics/DLLab/AixaAndrade/src/...
7      4    val  /archive/bioinformatics/DLLab/AixaAndrade/src/...
8      5  train  /archive/bioinformatics/DLLab/AixaAndrade/src/...
9      5    val  /archive/bioinformatics/DLLab/AixaAndrade/src/...
Reading paths, df head:
   Key  Split                                         LatentPath   Type  \
0  ae      1  /endosome/archive/bioinformatics/DLLab/src/Aix...  train
1  ae      1  /endosome/archive/bioinformatics/DLLab/src/Aix...    val
2  ae      1  /endosome/archive/bioinformatics/DLLab/src/Aix...   test
3  ae      2  /endosome/archive/bioinformatics/DLLab/src/Aix...  train
4  ae      2  /endosome/archive/bioinformatics/DLLab/src/Aix...    val

                                          InputsPath      latent_prefix  \
0  /archive/bioinformatics/DLLab/AixaAndrade/src/...  ae_latent_train_1
1  /archive/bioinformatics/DLLab/AixaAndrade/src/...    ae_latent_val_1
2                                                NaN   ae_latent_test_1
3  /archive/bioinformatics/DLLab/AixaAndrade/src/...  ae_latent_train_2
4  /archive/bioinformatics/DLLab/AixaAndrade/src/...    ae_latent_val_2

  input_prefix
0      train_1
1        val_1
2       test_1
3      train_2
4        val_2
Computing UMAP projections...
Index(['Key', 'Split', 'LatentPath', 'Type', 'InputsPath', 'latent_prefix',
       'input_prefix'],
      dtype='object')


Processing prefix: 0 train_1
Reading data from: /archive/bioinformatics/DLLab/AixaAndrade/src/gitfront/scMEDAL_for_scRNAseq/Experiments/data/HealthyHeart_data/log_transformed_3000hvggenes/splits/split_1/train

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Computing UMAP on 41544 cells × 3000 features, using 'X_pca'
UMAP shape: (41544, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Computing UMAP on 41544 cells × 50 features, using 'X'
UMAP shape: (41544, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Computing UMAP on 41544 cells × 50 features, using 'X'
UMAP shape: (41544, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Computing UMAP on 41544 cells × 50 features, using 'X'
UMAP shape: (41544, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Computing UMAP on 41544 cells × 50 features, using 'X'
UMAP shape: (41544, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Computing UMAP on 41544 cells × 50 features, using 'X'

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/sklearn/manifold/_spectral_embedding.py:273: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn(

UMAP shape: (41544, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Computing UMAP on 41544 cells × 50 features, using 'X'
UMAP shape: (41544, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Computing UMAP on 41544 cells × 50 features, using 'X'
UMAP shape: (41544, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Computing UMAP on 41544 cells × 50 features, using 'X'
UMAP shape: (41544, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Computing UMAP on 41544 cells × 50 features, using 'X'
UMAP shape: (41544, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Computing UMAP on 41544 cells × 50 features, using 'X'
UMAP shape: (41544, 2)
Computing UMAP on 291680 cells × 3000 features, using 'X_pca'
UMAP shape: (291680, 2)
I broke
Computing UMAP on 41544 cells × 3000 features, using 'X_pca'
UMAP shape: (41544, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Sampling 19 batches out of 147
Computing UMAP on 41544 cells × 3000 features, using 'X_pca'
UMAP shape: (41544, 2)
Plotting input latent space.. for 19

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Plotting ae_latent_train_1 latent space.. for 19
Computing UMAP on 41544 cells × 50 features, using 'X'
UMAP shape: (41544, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Plotting aec_latent_train_1 latent space.. for 19
Computing UMAP on 41544 cells × 50 features, using 'X'
UMAP shape: (41544, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Plotting scmedalfe_latent_train_1 latent space.. for 19
Computing UMAP on 41544 cells × 50 features, using 'X'
UMAP shape: (41544, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Plotting scmedalfec_latent_train_1 latent space.. for 19
Computing UMAP on 41544 cells × 50 features, using 'X'
UMAP shape: (41544, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Plotting scmedalre_latent_train_1 latent space.. for 19
Computing UMAP on 41544 cells × 50 features, using 'X'

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/sklearn/manifold/_spectral_embedding.py:273: UserWarning: Graph is not fully connected, spectral embedding may not work as expected.
  warnings.warn(

UMAP shape: (41544, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Plotting scVI_latent_train_1 latent space.. for 19
Computing UMAP on 41544 cells × 50 features, using 'X'
UMAP shape: (41544, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Plotting scANVI_latent_train_1 latent space.. for 19
Computing UMAP on 41544 cells × 50 features, using 'X'
UMAP shape: (41544, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Plotting scanorama_latent_train_1 latent space.. for 19
Computing UMAP on 41544 cells × 50 features, using 'X'
UMAP shape: (41544, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Plotting harmony_latent_train_1 latent space.. for 19
Computing UMAP on 41544 cells × 50 features, using 'X'
UMAP shape: (41544, 2)

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Plotting SAUCIE_latent_train_1 latent space.. for 19
Computing UMAP on 41544 cells × 50 features, using 'X'
UMAP shape: (41544, 2)

##### Step 4: Run genomaps on a subsample of the input data along with reconstructions from the scmedalfe and scmedalre models. 

Visualize selected batches to assess batch-specific effects in the reconstructed spaces, including conterfactual projections from scmedalre.

In [8]:

# Run genomaps on a subsample input+scmedalfe recon +scmedal re recon for different batches
batches = ["H0037_Apex", "HCAHeart7836681", "HCAHeart8102861", "H0015_septum"]
# for this genomap config, you need to compute first the reconstructions from scMEDAL-FE and scMEDAL-RE
selected_models = {k: model_folder_dict[k] for k in ("scmedalfe", "scmedalre")}
gfd = hh.genomap(selected_models,
                            n_batches = 147,
                            num_iter = 2, # for quick test, otherwise 100
                            cell_id_col = "_index",
                            gene_index_col = "_index",
                            celltype = ["Ventricular_Cardiomyocyte", "Endothelial", "Fibroblast", "Pericytes"],
                            batches=batches,
                            models=['scmedalre'],#if add_inputs_fe=True-> scmedalfe+ inputs are used for genomap creation by default, no need to add the to the list, 
                            types=["train"], 
                            splits=[1],
                            add_inputs_fe= True,
                            extra_recon = "fe",
                            min_val = -2,
                            max_val = 8)#,issparse=True )

Looking for outputs paths for the following models:dict_keys(['scmedalfe', 'scmedalre'])
Created df with input and recon paths
            Key  Split                                          ReconPath  \
0     scmedalfe      1  /endosome/archive/bioinformatics/DLLab/src/Aix...
1     scmedalfe      1  /endosome/archive/bioinformatics/DLLab/src/Aix...
2     scmedalfe      1  /endosome/archive/bioinformatics/DLLab/src/Aix...
3     scmedalfe      2  /endosome/archive/bioinformatics/DLLab/src/Aix...
4     scmedalfe      2  /endosome/archive/bioinformatics/DLLab/src/Aix...
...         ...    ...                                                ...
2230  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...
2231  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...
2232  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...
2233  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...
2234  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...

       Type                                         InputsPath  \
0     train  /archive/bioinformatics/DLLab/AixaAndrade/src/...
1       val  /archive/bioinformatics/DLLab/AixaAndrade/src/...
2      test                                                NaN
3     train  /archive/bioinformatics/DLLab/AixaAndrade/src/...
4       val  /archive/bioinformatics/DLLab/AixaAndrade/src/...
...     ...                                                ...
2230   test                                                NaN
2231   test                                                NaN
2232   test                                                NaN
2233   test                                                NaN
2234   test                                                NaN

                          recon_prefix
0                          recon_train
1                            recon_val
2                           recon_test
3                          recon_train
4                            recon_val
...                                ...
2230  recon_batch_test_HCAHeart7829978
2231  recon_batch_test_HCAHeart7844004
2232  recon_batch_test_HCAHeart7850546
2233  recon_batch_test_HCAHeart8102863
2234  recon_batch_test_HCAHeart7850540

[2235 rows x 6 columns]


Initialized genomap pipeline
sparse True
Computing genomap for ['train'] [1] ['scmedalre']
train 1 scmedalre
Searching input paths in df
            Key  Split                                          ReconPath  \
0     scmedalfe      1  /endosome/archive/bioinformatics/DLLab/src/Aix...
1     scmedalfe      1  /endosome/archive/bioinformatics/DLLab/src/Aix...
2     scmedalfe      1  /endosome/archive/bioinformatics/DLLab/src/Aix...
3     scmedalfe      2  /endosome/archive/bioinformatics/DLLab/src/Aix...
4     scmedalfe      2  /endosome/archive/bioinformatics/DLLab/src/Aix...
...         ...    ...                                                ...
2230  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...
2231  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...
2232  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...
2233  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...
2234  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...

       Type                                         InputsPath  \
0     train  /archive/bioinformatics/DLLab/AixaAndrade/src/...
1       val  /archive/bioinformatics/DLLab/AixaAndrade/src/...
2      test                                                NaN
3     train  /archive/bioinformatics/DLLab/AixaAndrade/src/...
4       val  /archive/bioinformatics/DLLab/AixaAndrade/src/...
...     ...                                                ...
2230   test                                                NaN
2231   test                                                NaN
2232   test                                                NaN
2233   test                                                NaN
2234   test                                                NaN

                          recon_prefix
0                          recon_train
1                            recon_val
2                           recon_test
3                          recon_train
4                            recon_val
...                                ...
2230  recon_batch_test_HCAHeart7829978
2231  recon_batch_test_HCAHeart7844004
2232  recon_batch_test_HCAHeart7850546
2233  recon_batch_test_HCAHeart8102863
2234  recon_batch_test_HCAHeart7850540

[2235 rows x 6 columns]
Searching input paths in df
            Key  Split                                          ReconPath  \
0     scmedalfe      1  /endosome/archive/bioinformatics/DLLab/src/Aix...
1     scmedalfe      1  /endosome/archive/bioinformatics/DLLab/src/Aix...
2     scmedalfe      1  /endosome/archive/bioinformatics/DLLab/src/Aix...
3     scmedalfe      2  /endosome/archive/bioinformatics/DLLab/src/Aix...
4     scmedalfe      2  /endosome/archive/bioinformatics/DLLab/src/Aix...
...         ...    ...                                                ...
2230  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...
2231  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...
2232  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...
2233  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...
2234  scmedalre      5  /endosome/archive/bioinformatics/DLLab/src/Aix...

       Type                                         InputsPath  \
0     train  /archive/bioinformatics/DLLab/AixaAndrade/src/...
1       val  /archive/bioinformatics/DLLab/AixaAndrade/src/...
2      test                                                NaN
3     train  /archive/bioinformatics/DLLab/AixaAndrade/src/...
4       val  /archive/bioinformatics/DLLab/AixaAndrade/src/...
...     ...                                                ...
2230   test                                                NaN
2231   test                                                NaN
2232   test                                                NaN
2233   test                                                NaN
2234   test                                                NaN

                          recon_prefix
0                          recon_train
1                            recon_val
2                           recon_test
3                          recon_train
4                            recon_val
...                                ...
2230  recon_batch_test_HCAHeart7829978
2231  recon_batch_test_HCAHeart7844004
2232  recon_batch_test_HCAHeart7850546
2233  recon_batch_test_HCAHeart8102863
2234  recon_batch_test_HCAHeart7850540

[2235 rows x 6 columns]
Reading data from: /archive/bioinformatics/DLLab/AixaAndrade/src/gitfront/scMEDAL_for_scRNAseq/Experiments/data/HealthyHeart_data/log_transformed_3000hvggenes/splits/split_1/train
batch_sel ['H0037_Apex', 'HCAHeart7836681', 'HCAHeart8102861', 'H0015_septum']
Selected 1 cell from batch H0037_Apex with celltype Ventricular_Cardiomyocyte.
Selected 1 cell from batch H0037_Apex with celltype Endothelial.
Selected 1 cell from batch H0037_Apex with celltype Fibroblast.
Selected 1 cell from batch H0037_Apex with celltype Pericytes.
No cells available for celltype ['Ventricular_Cardiomyocyte', 'Endothelial', 'Fibroblast', 'Pericytes'] in batch HCAHeart7836681. Skipping batch.
Selected 1 cell from batch HCAHeart7836681 with celltype Endothelial.
Selected 1 cell from batch HCAHeart7836681 with celltype Fibroblast.
Selected 1 cell from batch HCAHeart7836681 with celltype Pericytes.
No cells available for celltype ['Ventricular_Cardiomyocyte', 'Endothelial', 'Fibroblast', 'Pericytes'] in batch HCAHeart8102861. Skipping batch.
Selected 1 cell from batch HCAHeart8102861 with celltype Endothelial.
Selected 1 cell from batch HCAHeart8102861 with celltype Fibroblast.
Selected 1 cell from batch HCAHeart8102861 with celltype Pericytes.
Selected 1 cell from batch H0015_septum with celltype Ventricular_Cardiomyocyte.
Selected 1 cell from batch H0015_septum with celltype Endothelial.
Selected 1 cell from batch H0015_septum with celltype Fibroblast.
Selected 1 cell from batch H0015_septum with celltype Pericytes.
Selected 286 additional cells from specified celltypes.
input_train
Reading data from: /archive/bioinformatics/DLLab/AixaAndrade/src/gitfront/scMEDAL_for_scRNAseq/Experiments/data/HealthyHeart_data/log_transformed_3000hvggenes/splits/split_1/train
fe_ae_recon_train
recon_train
recon_batch_train_HCAHeart7656534
recon_batch_train_HCAHeart7844003
recon_batch_train_HCAHeart7757637
recon_batch_train_HCAHeart7833855
recon_batch_train_HCAHeart8287123
recon_batch_train_HCAHeart7843999
recon_batch_train_HCAHeart7850548
recon_batch_train_HCAHeart7656538
recon_batch_train_HCAHeart8102868
recon_batch_train_H0026_RV
recon_batch_train_HCAHeart7888924
recon_batch_train_HCAHeart7702873
recon_batch_train_HCAHeart7656535
recon_batch_train_HCAHeart7888927
recon_batch_train_HCAHeart7702877
recon_batch_train_HCAHeart7664653
recon_batch_train_H0026_RA
recon_batch_train_HCAHeart7850549
recon_batch_train_HCAHeart7844000
recon_batch_train_HCAHeart7745966
recon_batch_train_H0026_septum2
recon_batch_train_H0020_LV
recon_batch_train_H0035_LA
recon_batch_train_HCAHeart7880863
recon_batch_train_HCAHeart7836682
recon_batch_train_HCAHeart8102866
recon_batch_train_HCAHeart7702880
recon_batch_train_HCAHeart7888928
recon_batch_train_HCAHeart7850545
recon_batch_train_HCAHeart7698016
recon_batch_train_HCAHeart7905330
recon_batch_train_HCAHeart7833853
recon_batch_train_H0025_septum
recon_batch_train_H0035_septum
recon_batch_train_HCAHeart7850541
recon_batch_train_HCAHeart7656536
recon_batch_train_HCAHeart8287125
recon_batch_train_H0015_apex
recon_batch_train_HCAHeart7964513
recon_batch_train_H0015_septum
recon_batch_train_HCAHeart8102859
recon_batch_train_HCAHeart7844001
recon_batch_train_HCAHeart8102861
recon_batch_train_HCAHeart7905331
recon_batch_train_HCAHeart7728606
recon_batch_train_HCAHeart7702881
recon_batch_train_HCAHeart7702879
recon_batch_train_HCAHeart7751845
recon_batch_train_H0020_RV
recon_batch_train_HCAHeart7656539
recon_batch_train_HCAHeart7836681
recon_batch_train_HCAHeart7833852
recon_batch_train_HCAHeart7836683
recon_batch_train_HCAHeart7829978
recon_batch_train_H0020_apex
recon_batch_train_H0035_RV
recon_batch_train_HCAHeart7829976
recon_batch_train_HCAHeart7844002
recon_batch_train_HCAHeart7728608
recon_batch_train_HCAHeart7829977
recon_batch_train_HCAHeart8287127
recon_batch_train_HCAHeart7757636
recon_batch_train_HCAHeart8102867
recon_batch_train_H0037_septum
recon_batch_train_HCAHeart8287124
recon_batch_train_HCAHeart7888926
recon_batch_train_HCAHeart7833854
recon_batch_train_H0015_LA_new
recon_batch_train_HCAHeart8102858
recon_batch_train_HCAHeart7728605
recon_batch_train_HCAHeart7888922
recon_batch_train_HCAHeart7664652
recon_batch_train_HCAHeart7745969
recon_batch_train_HCAHeart7829979
recon_batch_train_H0025_apex
recon_batch_train_H0026_LA
recon_batch_train_HCAHeart8102860
recon_batch_train_HCAHeart7985089
recon_batch_train_HCAHeart7985087
recon_batch_train_HCAHeart7888923
recon_batch_train_HCAHeart7888929
recon_batch_train_H0037_LA_corr
recon_batch_train_HCAHeart7728607
recon_batch_train_HCAHeart7698017
recon_batch_train_H0035_RA
recon_batch_train_HCAHeart8287126
recon_batch_train_H0037_RV
recon_batch_train_HCAHeart7850546
recon_batch_train_H0037_Apex
recon_batch_train_HCAHeart8287128
recon_batch_train_HCAHeart7850547
recon_batch_train_H0015_LV
recon_batch_train_HCAHeart8102863
recon_batch_train_H0020_RA
recon_batch_train_H0037_RA_corr
recon_batch_train_HCAHeart7880860
recon_batch_train_H0025_RA
recon_batch_train_HCAHeart7905329
recon_batch_train_HCAHeart7745968
recon_batch_train_HCAHeart7835148
recon_batch_train_HCAHeart7850542
recon_batch_train_HCAHeart7835149
recon_batch_train_HCAHeart7850539
recon_batch_train_HCAHeart7905328
recon_batch_train_H0037_LV
recon_batch_train_H0025_LA
recon_batch_train_HCAHeart7745967
recon_batch_train_HCAHeart7656537
recon_batch_train_HCAHeart7664654
recon_batch_train_HCAHeart8102864
recon_batch_train_HCAHeart7698015
recon_batch_train_HCAHeart7850544
recon_batch_train_HCAHeart7745970
recon_batch_train_HCAHeart7880861
recon_batch_train_HCAHeart7702878
recon_batch_train_HCAHeart7702876
recon_batch_train_H0026_apex
recon_batch_train_HCAHeart7905332
recon_batch_train_HCAHeart7888925
recon_batch_train_HCAHeart7728609
recon_batch_train_HCAHeart7702882
recon_batch_train_HCAHeart7757638
recon_batch_train_HCAHeart7702875
recon_batch_train_HCAHeart7850543
recon_batch_train_H0025_LV
recon_batch_train_H0026_LV_V3
recon_batch_train_HCAHeart7606896
recon_batch_train_HCAHeart7985088
recon_batch_train_H0015_RA
recon_batch_train_HCAHeart8102865
recon_batch_train_HCAHeart8102862
recon_batch_train_HCAHeart7757639
recon_batch_train_HCAHeart7844004
recon_batch_train_H0025_RV
recon_batch_train_H0015_RV
recon_batch_train_H0020_septum
recon_batch_train_HCAHeart7728604
recon_batch_train_HCAHeart7836684
recon_batch_train_HCAHeart7850551
recon_batch_train_H0020_LA_new
recon_batch_train_H0035_apex
recon_batch_train_H0035_LV
recon_batch_train_HCAHeart7702874
recon_batch_train_HCAHeart7880862
recon_batch_train_HCAHeart7905327
recon_batch_train_HCAHeart7985086
Shape of concatenated x: (44402, 2916)
Shape of concatenated obs: (44402, 21)
created folder path: /endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/HH/compare_models/log_transformed_3000hvggenes/HH_default_500/CMmultibatch_300_cells_per_batch_147batches_Ventricular_Cardiomyocyte_Endothelial_Fibroblast_Pericytes_with_2fe_input
Folder already exists: /endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/HH/compare_models/log_transformed_3000hvggenes/HH_default_500/CMmultibatch_300_cells_per_batch_147batches_Ventricular_Cardiomyocyte_Endothelial_Fibroblast_Pericytes_with_2fe_input

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

batches 2 select from ['H0037_Apex', 'HCAHeart7836681', 'HCAHeart8102861', 'H0015_septum']
b'TCACTCGGTTCTTGTT-1-H0037_Apex' comes from batch H0037_Apex
b'GTACAGTTCCAATGCA-1-H0037_Apex' comes from batch H0037_Apex
b'CCACTTGGTTGGCTAT-1-H0037_Apex' comes from batch H0037_Apex
b'GCCATGGGTGACAGGT-1-H0037_Apex' comes from batch H0037_Apex
b'CATGACACAATCGGTT-1-HCAHeart7836681' comes from batch HCAHeart7836681
b'CATGGCGAGCGTAATA-1-HCAHeart7836681' comes from batch HCAHeart7836681
b'AGGGTGATCAACACTG-1-HCAHeart7836681' comes from batch HCAHeart7836681
b'TAGGTACAGACATATG-1-HCAHeart8102861' comes from batch HCAHeart8102861
b'TTCTAGTGTGAACCGA-1-HCAHeart8102861' comes from batch HCAHeart8102861
b'GTCGAATGTAGCACAG-1-HCAHeart8102861' comes from batch HCAHeart8102861
b'TCCGAAAAGAAGGGAT-1-H0015_septum' comes from batch H0015_septum
b'CTATAGGTCTCTATAC-1-H0015_septum' comes from batch H0015_septum
b'CGAGGCTCAGAGGACT-1-H0015_septum' comes from batch H0015_septum
b'CTCAATTAGCACTCTA-1-H0015_septum' comes from batch H0015_septum
original batch list: ['H0037_Apex', 'H0037_Apex', 'H0037_Apex', 'H0037_Apex', 'HCAHeart7836681', 'HCAHeart7836681', 'HCAHeart7836681', 'HCAHeart8102861', 'HCAHeart8102861', 'HCAHeart8102861', 'H0015_septum', 'H0015_septum', 'H0015_septum', 'H0015_septum']
Reading data from: /endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/HH/compare_models/log_transformed_3000hvggenes/HH_default_500/CMmultibatch_300_cells_per_batch_147batches_Ventricular_Cardiomyocyte_Endothelial_Fibroblast_Pericytes_with_2fe_input

/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
/archive/bioinformatics/DLLab/shared/CondaEnvironments/scMEDAL/lib/python3.8/site-packages/anndata/_core/anndata.py:121: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)

Input does not contain NaNs
subset_input_z_scores shape: (44402, 2916)

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:261: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.1, 1, 1])  # Adjust layout to make room for colorbar

Missing indices: set()
n cell indexes Index([    0,   298,   596,   894,  1192,  1490,  1788,  2086,  2384,  2682,
       ...
       41422, 41720, 42018, 42316, 42614, 42912, 43210, 43508, 43806, 44104],
      dtype='int64', length=149)
Shape of std_across_batches: (54, 54)


plotting big panel for b'TCACTCGGTTCTTGTT-1-H0037_Apex' with original batch H0037_Apex and celltype Ventricular_Cardiomyocyte, n recons: 149

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

n cell indexes for batch CF recon Index([0, 298, 12516, 13410, 15794, 27118], dtype='int64')
plotting small panel for b'TCACTCGGTTCTTGTT-1-H0037_Apex' with original batch H0037_Apex and celltype Ventricular_Cardiomyocyte, n recons: 6

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

plotting same panel but with no gene labels
n cell indexes Index([    1,   299,   597,   895,  1193,  1491,  1789,  2087,  2385,  2683,
       ...
       41423, 41721, 42019, 42317, 42615, 42913, 43211, 43509, 43807, 44105],
      dtype='int64', length=149)
Shape of std_across_batches: (54, 54)


plotting big panel for b'GTACAGTTCCAATGCA-1-H0037_Apex' with original batch H0037_Apex and celltype Endothelial, n recons: 149

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

n cell indexes for batch CF recon Index([1, 299, 12517, 13411, 15795, 27119], dtype='int64')
plotting small panel for b'GTACAGTTCCAATGCA-1-H0037_Apex' with original batch H0037_Apex and celltype Endothelial, n recons: 6

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

plotting same panel but with no gene labels
n cell indexes Index([    2,   300,   598,   896,  1194,  1492,  1790,  2088,  2386,  2684,
       ...
       41424, 41722, 42020, 42318, 42616, 42914, 43212, 43510, 43808, 44106],
      dtype='int64', length=149)
Shape of std_across_batches: (54, 54)


plotting big panel for b'CCACTTGGTTGGCTAT-1-H0037_Apex' with original batch H0037_Apex and celltype Fibroblast, n recons: 149

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

n cell indexes for batch CF recon Index([2, 300, 12518, 13412, 15796, 27120], dtype='int64')
plotting small panel for b'CCACTTGGTTGGCTAT-1-H0037_Apex' with original batch H0037_Apex and celltype Fibroblast, n recons: 6

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

plotting same panel but with no gene labels
n cell indexes Index([  291,   589,   887,  1185,  1483,  1781,  2079,  2377,  2675,  2973,
       ...
       41713, 42011, 42309, 42607, 42905, 43203, 43501, 43799, 44097, 44395],
      dtype='int64', length=149)
Shape of std_across_batches: (54, 54)


plotting big panel for b'GCCATGGGTGACAGGT-1-H0037_Apex' with original batch H0037_Apex and celltype Pericytes, n recons: 149

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

n cell indexes for batch CF recon Index([291, 589, 12807, 13701, 16085, 27409], dtype='int64')
plotting small panel for b'GCCATGGGTGACAGGT-1-H0037_Apex' with original batch H0037_Apex and celltype Pericytes, n recons: 6

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

plotting same panel but with no gene labels
n cell indexes Index([    4,   302,   600,   898,  1196,  1494,  1792,  2090,  2388,  2686,
       ...
       41426, 41724, 42022, 42320, 42618, 42916, 43214, 43512, 43810, 44108],
      dtype='int64', length=149)
Shape of std_across_batches: (54, 54)


plotting big panel for b'CATGACACAATCGGTT-1-HCAHeart7836681' with original batch HCAHeart7836681 and celltype Endothelial, n recons: 149

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

n cell indexes for batch CF recon Index([4, 302, 12520, 13414, 15798, 27122], dtype='int64')
plotting small panel for b'CATGACACAATCGGTT-1-HCAHeart7836681' with original batch HCAHeart7836681 and celltype Endothelial, n recons: 6

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

plotting same panel but with no gene labels
n cell indexes Index([  215,   513,   811,  1109,  1407,  1705,  2003,  2301,  2599,  2897,
       ...
       41637, 41935, 42233, 42531, 42829, 43127, 43425, 43723, 44021, 44319],
      dtype='int64', length=149)
Shape of std_across_batches: (54, 54)


plotting big panel for b'CATGGCGAGCGTAATA-1-HCAHeart7836681' with original batch HCAHeart7836681 and celltype Fibroblast, n recons: 149

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

n cell indexes for batch CF recon Index([215, 513, 12731, 13625, 16009, 27333], dtype='int64')
plotting small panel for b'CATGGCGAGCGTAATA-1-HCAHeart7836681' with original batch HCAHeart7836681 and celltype Fibroblast, n recons: 6

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

plotting same panel but with no gene labels
n cell indexes Index([    6,   304,   602,   900,  1198,  1496,  1794,  2092,  2390,  2688,
       ...
       41428, 41726, 42024, 42322, 42620, 42918, 43216, 43514, 43812, 44110],
      dtype='int64', length=149)
Shape of std_across_batches: (54, 54)


plotting big panel for b'AGGGTGATCAACACTG-1-HCAHeart7836681' with original batch HCAHeart7836681 and celltype Pericytes, n recons: 149

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

n cell indexes for batch CF recon Index([6, 304, 12522, 13416, 15800, 27124], dtype='int64')
plotting small panel for b'AGGGTGATCAACACTG-1-HCAHeart7836681' with original batch HCAHeart7836681 and celltype Pericytes, n recons: 6

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

plotting same panel but with no gene labels
n cell indexes Index([  141,   439,   737,  1035,  1333,  1631,  1929,  2227,  2525,  2823,
       ...
       41563, 41861, 42159, 42457, 42755, 43053, 43351, 43649, 43947, 44245],
      dtype='int64', length=149)
Shape of std_across_batches: (54, 54)


plotting big panel for b'TAGGTACAGACATATG-1-HCAHeart8102861' with original batch HCAHeart8102861 and celltype Endothelial, n recons: 149

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

n cell indexes for batch CF recon Index([141, 439, 12657, 13551, 15935, 27259], dtype='int64')
plotting small panel for b'TAGGTACAGACATATG-1-HCAHeart8102861' with original batch HCAHeart8102861 and celltype Endothelial, n recons: 6

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

plotting same panel but with no gene labels
n cell indexes Index([    8,   306,   604,   902,  1200,  1498,  1796,  2094,  2392,  2690,
       ...
       41430, 41728, 42026, 42324, 42622, 42920, 43218, 43516, 43814, 44112],
      dtype='int64', length=149)
Shape of std_across_batches: (54, 54)


plotting big panel for b'TTCTAGTGTGAACCGA-1-HCAHeart8102861' with original batch HCAHeart8102861 and celltype Fibroblast, n recons: 149

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

n cell indexes for batch CF recon Index([8, 306, 12524, 13418, 15802, 27126], dtype='int64')
plotting small panel for b'TTCTAGTGTGAACCGA-1-HCAHeart8102861' with original batch HCAHeart8102861 and celltype Fibroblast, n recons: 6

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

plotting same panel but with no gene labels
n cell indexes Index([    9,   307,   605,   903,  1201,  1499,  1797,  2095,  2393,  2691,
       ...
       41431, 41729, 42027, 42325, 42623, 42921, 43219, 43517, 43815, 44113],
      dtype='int64', length=149)
Shape of std_across_batches: (54, 54)


plotting big panel for b'GTCGAATGTAGCACAG-1-HCAHeart8102861' with original batch HCAHeart8102861 and celltype Pericytes, n recons: 149

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

n cell indexes for batch CF recon Index([9, 307, 12525, 13419, 15803, 27127], dtype='int64')
plotting small panel for b'GTCGAATGTAGCACAG-1-HCAHeart8102861' with original batch HCAHeart8102861 and celltype Pericytes, n recons: 6

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

plotting same panel but with no gene labels
n cell indexes Index([   69,   367,   665,   963,  1261,  1559,  1857,  2155,  2453,  2751,
       ...
       41491, 41789, 42087, 42385, 42683, 42981, 43279, 43577, 43875, 44173],
      dtype='int64', length=149)
Shape of std_across_batches: (54, 54)


plotting big panel for b'TCCGAAAAGAAGGGAT-1-H0015_septum' with original batch H0015_septum and celltype Ventricular_Cardiomyocyte, n recons: 149

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

n cell indexes for batch CF recon Index([69, 367, 12585, 13479, 15863, 27187], dtype='int64')
plotting small panel for b'TCCGAAAAGAAGGGAT-1-H0015_septum' with original batch H0015_septum and celltype Ventricular_Cardiomyocyte, n recons: 6

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

plotting same panel but with no gene labels
n cell indexes Index([   11,   309,   607,   905,  1203,  1501,  1799,  2097,  2395,  2693,
       ...
       41433, 41731, 42029, 42327, 42625, 42923, 43221, 43519, 43817, 44115],
      dtype='int64', length=149)
Shape of std_across_batches: (54, 54)


plotting big panel for b'CTATAGGTCTCTATAC-1-H0015_septum' with original batch H0015_septum and celltype Endothelial, n recons: 149

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

n cell indexes for batch CF recon Index([11, 309, 12527, 13421, 15805, 27129], dtype='int64')
plotting small panel for b'CTATAGGTCTCTATAC-1-H0015_septum' with original batch H0015_septum and celltype Endothelial, n recons: 6

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

plotting same panel but with no gene labels
n cell indexes Index([  207,   505,   803,  1101,  1399,  1697,  1995,  2293,  2591,  2889,
       ...
       41629, 41927, 42225, 42523, 42821, 43119, 43417, 43715, 44013, 44311],
      dtype='int64', length=149)
Shape of std_across_batches: (54, 54)


plotting big panel for b'CGAGGCTCAGAGGACT-1-H0015_septum' with original batch H0015_septum and celltype Fibroblast, n recons: 149

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

n cell indexes for batch CF recon Index([207, 505, 12723, 13617, 16001, 27325], dtype='int64')
plotting small panel for b'CGAGGCTCAGAGGACT-1-H0015_septum' with original batch H0015_septum and celltype Fibroblast, n recons: 6

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

plotting same panel but with no gene labels
n cell indexes Index([   13,   311,   609,   907,  1205,  1503,  1801,  2099,  2397,  2695,
       ...
       41435, 41733, 42031, 42329, 42627, 42925, 43223, 43521, 43819, 44117],
      dtype='int64', length=149)
Shape of std_across_batches: (54, 54)


plotting big panel for b'CTCAATTAGCACTCTA-1-H0015_septum' with original batch H0015_septum and celltype Pericytes, n recons: 149

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

n cell indexes for batch CF recon Index([13, 311, 12529, 13423, 15807, 27131], dtype='int64')
plotting small panel for b'CTCAATTAGCACTCTA-1-H0015_septum' with original batch H0015_septum and celltype Pericytes, n recons: 6

/endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/utils/genomaps_utils.py:991: UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.
  plt.tight_layout(rect=[0, 0.03, 0.9, 0.97])

plotting same panel but with no gene labels

## Run the Mixed Effects Classifier (MEC) on latent spaces generated by scmedalfe and scmedalre.

Classification target: 6 tissues 

Run $python\ mec\_hh.py$

In [13]:
# Now get a summary table of all mec results
from utils.compare_results_utils import get_all_mec_metrics
df,_ = get_all_mec_metrics(HH_OUTPUTS_DIR,HH_EXPERIMENT_NAME, split='test')
df

MEC RF summary able saved to /endosome/archive/bioinformatics/DLLab/src/AixaAndrade/gitfront/dev2/scMEDAL_for_scRNAseq/outputs/HH/latent_space/log_transformed_3000hvggenes/mec/MEC_RF_summary.csv

,latent,RFAccuracy_mean,RFAccuracy_95CI_lower,RFAccuracy_95CI_upper,RFBalancedAccuracy_mean,RFBalancedAccuracy_95CI_lower,RFBalancedAccuracy_95CI_upper,ChanceAccuracy_mean,ChanceAccuracy_95CI_lower,ChanceAccuracy_95CI_upper,run_name
0,scANVI_latent,35.63,35.11,36.14,34.84,34.11,35.57,17.91,17.73,18.08,scANVI_latent_n_pred-6_bio_col-TissueDetail_20...
0,scVI_latent,40.83,39.39,42.27,41.20,39.43,42.96,17.91,17.73,18.08,scVI_latent_n_pred-6_bio_col-TissueDetail_2025...
0,scVI_latent_re_latent-scmedalre_latent,97.73,96.31,99.15,97.63,96.32,98.93,17.91,17.73,18.08,scVI_latent_re_latent-scmedalre_latent_n_pred-...